tile_texture = {}
tile_solid = {
    0: False,
    1: True,
    2: True,
    3: True,
    4: True,
    5: True,
    6: True,
    7: True,
    8: True,
    9: True,
    10: False,

    11: True,
    12: True,
    13: True,
    14: True,
    15: True,
    16: True,
    17: True,
    18: True,

    19: True,
    20: True,
    21: True,
    22: True,
    23: True,
    24: True,
    25: True,
    }
tile_visible = { #Sprite tiles are not visible
    0: False,
    1: True,
    2: True,
    3: True,
    4: True,
    5: True,
    6: True,
    7: True,
    8: False,
    9: False,
    10: False,

    11: True,
    12: True,
    13: True,
    14: True,
    15: True,
    16: False,
    17: False,
    18: False,

    19: True,
    20: True,
    21: True,
    22: True,
    23: True,
    24: True,
    25: False,
    }
texture_type = { #air, wall, trigger, sprite
    0: 'air',
    1: 'wall',
    2: 'wall',
    3: 'wall',
    4: 'wall',
    5: 'end',
    6: 'vdoor',
    7: 'hdoor',
    8: 'sprite',
    9: 'sprite',
    10: 'sprite',

    11: 'wall',
    12: 'wall',
    13: 'wall',
    14: 'wall',
    15: 'end',
    16: 'sprite',
    17: 'sprite',
    18: 'sprite',

    19: 'wall',
    20: 'wall',
    21: 'wall',
    22: 'end',
    23: 'vdoor',
    24: 'hdoor',
    25: 'sprite',
    }